brakeman:
  comment: true
  exit_code: 0
  ignore: true
bundle-audit:
  comment: true
  exit_code: 0
  ignore: true
eslint:
  comment: true
  exit_code: 256
  ignore: false
rails_best_practices:
  comment: true
  exit_code: 256
  ignore: true
reek:
  comment: true
  exit_code: 512
  ignore: true
rspec:
  comment: true
  exit_code: 256
  ignore: true
rubocop:
  comment: true
  exit_code: 0
  ignore: false
scss-lint:
  comment: true
  exit_code: 0
  ignore: true
