default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: dev_user
  password: 12345678
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: cv_maker_development

test:
  <<: *default
  database: cv_maker_test

production:
  <<: *default
  database: cv_maker_production
  username: cv_maker
  password: <%= ENV['CV_MAKER_DATABASE_PASSWORD'] %>
